# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DuckLake
email: quack@duckdb.org
description: >-
  DuckLake leverages DuckDB and your favorite SQL database (SQLite, Postgres, MySQL) to provide ACID transactions, schema evolution, and time travel for your Parquet data lake, without the complexity of traditional Lakehouse catalogs.
baseurl: ""
url: "https://ducklake.select"

# DuckLake Versioning
stable_ducklake_version: "0.2"
preview_ducklake_version: "0.3-dev"

livereload: true
highlighter: rouge
incremental: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  smart_quotes: ["apos", "apos", "quot", "quot"]
theme: minima
plugins:
  - jekyll-regex-replace
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-git-hash
  - jekyll-toc

# Posts configuration
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
  media:
    output: true
    permalink: /media/:title/

excerpt_separator: <!--more-->
future: true

last-modified-at:
  date-format: '%Y-%m-%d'

twitter:
  username: DuckLake
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: /images/sharingducklake.png
      toc: true

repository: "duckdb/ducklake-web"

star_count: "0.0k"

toc:
  min_level: 1
  max_level: 3
  ordered_list: false

exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', 'vendor/bundle', 'vendor/cache', 'vendor/gems', 'vendor/ruby', 'bundle']
